import argparse
import time
from pathlib import Path

import numpy as np


SCRIPT_DIR = Path(__file__).resolve().parent


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Watch fft.npy generated by analyzer_from_fpga_fft.py and plot it as a spectrogram."
    )
    parser.add_argument(
        "--fft-file",
        type=Path,
        default=SCRIPT_DIR / "fft.npy",
        help="Path to fft.npy generated by the analyzer",
    )
    parser.add_argument("--rate", type=int, default=48000, help="Sample rate used by the FPGA stream")
    parser.add_argument("--frame-bins", type=int, default=512, help="Complex bins per FPGA FFT frame")
    parser.add_argument("--max-freq", type=float, default=20000.0, help="Maximum frequency shown on the plot")
    parser.add_argument("--step-hz", type=float, default=1000.0, help="Y-axis label spacing in Hz")
    parser.add_argument("--backend", default="TkAgg", help="Matplotlib backend for the interactive window")
    args = parser.parse_args()

    if args.rate <= 0:
        parser.error("--rate must be positive")
    if args.frame_bins <= 0:
        parser.error("--frame-bins must be positive")
    if args.max_freq <= 0:
        parser.error("--max-freq must be positive")
    if args.step_hz <= 0:
        parser.error("--step-hz must be positive")

    try:
        import matplotlib
    except ImportError as exc:
        raise SystemExit(
            "matplotlib is required for plotFFT.py. Install the project requirements first."
        ) from exc

    matplotlib.use(args.backend)
    import matplotlib.pyplot as plt

    fft_path = args.fft_file.resolve()
    freq_per_bin = args.rate / args.frame_bins

    fig, ax = plt.subplots()
    plt.ion()
    plt.show(block=False)

    fft_cache = None
    last_mtime = 0.0

    while True:
        if not fft_path.exists():
            plt.pause(0.1)
            continue

        mtime = fft_path.stat().st_mtime
        if fft_cache is not None and mtime == last_mtime:
            plt.pause(0.1)
            continue

        print("FFT atualizada:", fft_path, flush=True)
        fft_cache = np.load(fft_path)
        last_mtime = mtime

        if fft_cache.ndim != 2 or fft_cache.shape[0] == 0 or fft_cache.shape[1] == 0:
            print("fft.npy tem formato invalido para plot:", fft_cache.shape, flush=True)
            plt.pause(0.1)
            continue

        max_bin = min(fft_cache.shape[1], int(args.max_freq / freq_per_bin) + 1)
        fft_mag = np.abs(fft_cache[:, :max_bin])
        fft_mag = 20.0 * np.log10(fft_mag + 1e-9)

        vmax = float(np.max(fft_mag))
        vmin = vmax - 50.0

        ax.clear()
        ax.imshow(
            fft_mag.T,
            aspect="auto",
            origin="lower",
            cmap="inferno",
            vmin=vmin,
            vmax=vmax,
        )

        ax.set_title("FFT ao longo do tempo")
        ax.set_xlabel("Tempo (frames)")
        ax.set_ylabel("Frequencia (Hz)")

        freq_limit = min(args.max_freq, (max_bin - 1) * freq_per_bin)
        freqs_hz = np.arange(0.0, freq_limit + args.step_hz, args.step_hz)
        yticks = freqs_hz / freq_per_bin
        valid = yticks < max_bin
        ax.set_yticks(yticks[valid])
        ax.set_yticklabels([f"{int(freq)}" for freq in freqs_hz[valid]])

        fig.canvas.draw()
        fig.canvas.flush_events()
        plt.pause(0.01)
        time.sleep(0.05)


if __name__ == "__main__":
    raise SystemExit(main())
