#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Capture one shared raw I2S mirror dump and verify it with multiple channel-mode scenarios.

Artifacts:
- shared raw capture (`mirror_capture.raw`)
- optional auto-mode CSV (`mirror_capture_auto.csv`)
- one verifier log per scenario
- one JSON summary per scenario
- a TSV summary aggregating the main metrics
- a replay script with the exact commands used

Usage:
  ./run_channel_debug_matrix.sh [options]

Options:
  -D, --device DEV             ALSA device (default: auto)
  -r, --rate HZ                Sample rate (default: 48828)
      --frame-bins N           Samples per FFT window (default: 512)
      --useful-bins N          Magnitude bins kept per window (default: 256)
      --seconds S              Shared raw capture time (default: 12)
      --chunk-frames N         Logger read size in stereo frames (default: 4096)
      --channel-modes LIST     Comma or space separated list (default: auto,left,right)
      --sample-shift-bits N    Arithmetic right shift before analysis (default: 0)
      --keep-dc                Keep the DC component before FFT
      --capture-backend MODE   auto, arecord or alsa-c (default: auto)
      --capture-binary PATH    Explicit path to native ALSA helper
      --output-dir DIR         Output directory (default: ./debug_runs/<timestamp>)
      --python BIN             Python interpreter to use
      --dry-run                Print commands without executing them
  -h, --help                   Show this help
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_PYTHON="${SCRIPT_DIR}/.venv/bin/python"
LOGGER_PATH="${SCRIPT_DIR}/fft_i2s_logger.py"
VERIFY_PATH="${SCRIPT_DIR}/verify_transport_stream.py"

DEVICE="${AUDIO_DEVICE:-auto}"
RATE=48828
FRAME_BINS=512
USEFUL_BINS=256
CAPTURE_SECONDS=12
CHUNK_FRAMES=4096
CHANNEL_MODES_RAW="auto,left,right"
SAMPLE_SHIFT_BITS=0
KEEP_DC=0
CAPTURE_BACKEND="auto"
CAPTURE_BINARY=""
OUTPUT_DIR=""
PYTHON_BIN="${DEFAULT_PYTHON}"
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    -D|--device)
      DEVICE="$2"
      shift 2
      ;;
    -r|--rate)
      RATE="$2"
      shift 2
      ;;
    --frame-bins)
      FRAME_BINS="$2"
      shift 2
      ;;
    --useful-bins)
      USEFUL_BINS="$2"
      shift 2
      ;;
    --seconds)
      CAPTURE_SECONDS="$2"
      shift 2
      ;;
    --chunk-frames)
      CHUNK_FRAMES="$2"
      shift 2
      ;;
    --channel-modes)
      CHANNEL_MODES_RAW="$2"
      shift 2
      ;;
    --sample-shift-bits)
      SAMPLE_SHIFT_BITS="$2"
      shift 2
      ;;
    --keep-dc)
      KEEP_DC=1
      shift
      ;;
    --capture-backend)
      CAPTURE_BACKEND="$2"
      shift 2
      ;;
    --capture-binary)
      CAPTURE_BINARY="$2"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --python)
      PYTHON_BIN="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ! -x "${PYTHON_BIN}" ]]; then
  if command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python3)"
  else
    echo "Python interpreter not found: ${PYTHON_BIN}" >&2
    exit 1
  fi
fi

if [[ ! -f "${LOGGER_PATH}" || ! -f "${VERIFY_PATH}" ]]; then
  echo "Required utilities not found under ${SCRIPT_DIR}" >&2
  exit 1
fi

timestamp="$(date +%Y%m%d_%H%M%S)"
if [[ -z "${OUTPUT_DIR}" ]]; then
  OUTPUT_DIR="${SCRIPT_DIR}/debug_runs/${timestamp}"
fi
mkdir -p "${OUTPUT_DIR}"

RAW_CAPTURE_PATH="${OUTPUT_DIR}/mirror_capture.raw"
AUTO_CSV_PATH="${OUTPUT_DIR}/mirror_capture_auto.csv"
SUMMARY_PATH="${OUTPUT_DIR}/scenario_summary.tsv"
README_PATH="${OUTPUT_DIR}/README.txt"
COMMANDS_PATH="${OUTPUT_DIR}/replay_commands.sh"
SESSION_INFO_PATH="${OUTPUT_DIR}/session_info.txt"

normalize_list() {
  local raw="$1"
  raw="${raw//,/ }"
  raw="$(echo "${raw}" | xargs || true)"
  printf '%s\n' "${raw}"
}

CHANNEL_MODES_NORM="$(normalize_list "${CHANNEL_MODES_RAW}")"
read -r -a CHANNEL_MODES <<<"${CHANNEL_MODES_NORM}"
if [[ ${#CHANNEL_MODES[@]} -eq 0 ]]; then
  echo "No channel modes were provided." >&2
  exit 1
fi

{
  echo "#!/usr/bin/env bash"
  echo "set -euo pipefail"
  echo
  echo "# Commands generated by run_channel_debug_matrix.sh"
} > "${COMMANDS_PATH}"
chmod +x "${COMMANDS_PATH}"

{
  echo "Mic mirror debug capture set"
  echo "generated_at=$(date -Is)"
  echo "script=${SCRIPT_DIR}/run_channel_debug_matrix.sh"
  echo "python=${PYTHON_BIN}"
  echo "device=${DEVICE}"
  echo "rate=${RATE}"
  echo "frame_bins=${FRAME_BINS}"
  echo "useful_bins=${USEFUL_BINS}"
  echo "seconds=${CAPTURE_SECONDS}"
  echo "chunk_frames=${CHUNK_FRAMES}"
  echo "channel_modes=${CHANNEL_MODES_NORM}"
  echo "sample_shift_bits=${SAMPLE_SHIFT_BITS}"
  echo "keep_dc=${KEEP_DC}"
  echo "capture_backend=${CAPTURE_BACKEND}"
  echo "capture_binary=${CAPTURE_BINARY:-auto}"
  echo "output_dir=${OUTPUT_DIR}"
} > "${SESSION_INFO_PATH}"

{
  echo "Mic mirror debug session"
  echo
  echo "Capture file:"
  echo "- ${RAW_CAPTURE_PATH}"
  echo
  echo "Scenarios:"
  for mode in "${CHANNEL_MODES[@]}"; do
    echo "- channel_mode=${mode}"
  done
} > "${README_PATH}"

{
  printf "scenario\tstatus\tsample_count\twindow_count\tdominant_channel\tleft_mean_abs\tright_mean_abs\tleft_nonzero_ratio\tright_nonzero_ratio\tmean_correlation_lr\tpeak_frequency_hz\n"
} > "${SUMMARY_PATH}"

logger_cmd=(
  "${PYTHON_BIN}" "${LOGGER_PATH}"
  "--device" "${DEVICE}"
  "--rate" "${RATE}"
  "--chunk-frames" "${CHUNK_FRAMES}"
  "--seconds" "${CAPTURE_SECONDS}"
  "--capture-backend" "${CAPTURE_BACKEND}"
  "--channel-mode" "auto"
  "--sample-shift-bits" "${SAMPLE_SHIFT_BITS}"
  "--raw-out" "${RAW_CAPTURE_PATH}"
  "--csv" "${AUTO_CSV_PATH}"
)
if [[ -n "${CAPTURE_BINARY}" ]]; then
  logger_cmd+=("--capture-binary" "${CAPTURE_BINARY}")
fi

printf '%q ' "${logger_cmd[@]}" >> "${COMMANDS_PATH}"
printf '\n\n' >> "${COMMANDS_PATH}"

echo "Shared capture command:"
printf '  %q' "${logger_cmd[@]}"
printf '\n'

if [[ "${DRY_RUN}" -eq 0 ]]; then
  "${logger_cmd[@]}"
fi

for mode in "${CHANNEL_MODES[@]}"; do
  scenario="channel_${mode}"
  log_path="${OUTPUT_DIR}/${scenario}.log"
  json_path="${OUTPUT_DIR}/${scenario}.json"

  verify_cmd=(
    "${PYTHON_BIN}" "${VERIFY_PATH}"
    "--raw" "${RAW_CAPTURE_PATH}"
    "--rate" "${RATE}"
    "--frame-bins" "${FRAME_BINS}"
    "--useful-bins" "${USEFUL_BINS}"
    "--channel-mode" "${mode}"
    "--sample-shift-bits" "${SAMPLE_SHIFT_BITS}"
    "--json-out" "${json_path}"
  )
  if [[ "${KEEP_DC}" -eq 1 ]]; then
    verify_cmd+=("--keep-dc")
  fi

  printf '%q ' "${verify_cmd[@]}" >> "${COMMANDS_PATH}"
  printf ' > %q\n\n' "${log_path}" >> "${COMMANDS_PATH}"

  echo "Scenario ${scenario}:"
  printf '  %q' "${verify_cmd[@]}"
  printf '\n'

  status="OK"
  if [[ "${DRY_RUN}" -eq 0 ]]; then
    if ! "${verify_cmd[@]}" > "${log_path}" 2>&1; then
      status="FAIL"
    fi
  else
    : > "${log_path}"
    printf '{ "sample_count": 0, "window_count": 0, "dominant_channel": "%s", "left_mean_abs": 0, "right_mean_abs": 0, "left_nonzero_ratio": 0, "right_nonzero_ratio": 0, "mean_correlation_lr": 0, "peak_frequency_hz": 0 }\n' "${mode}" > "${json_path}"
  fi

  summary_row="$("${PYTHON_BIN}" - <<'PY' "${json_path}" "${scenario}" "${status}"
import json
import sys
from pathlib import Path

json_path = Path(sys.argv[1])
scenario = sys.argv[2]
status = sys.argv[3]

if json_path.exists():
    payload = json.loads(json_path.read_text(encoding="utf-8"))
else:
    payload = {}

fields = [
    scenario,
    status,
    str(payload.get("sample_count", "")),
    str(payload.get("window_count", "")),
    str(payload.get("dominant_channel", "")),
    str(payload.get("left_mean_abs", "")),
    str(payload.get("right_mean_abs", "")),
    str(payload.get("left_nonzero_ratio", "")),
    str(payload.get("right_nonzero_ratio", "")),
    str(payload.get("mean_correlation_lr", "")),
    str(payload.get("peak_frequency_hz", "")),
]
print("\t".join(fields))
PY
)"
  printf '%s\n' "${summary_row}" >> "${SUMMARY_PATH}"
done

echo "Summary TSV: ${SUMMARY_PATH}"
echo "Replay commands: ${COMMANDS_PATH}"
echo "Session info: ${SESSION_INFO_PATH}"
